version: '3.8'
# docker-compose -f docker-compose-app-v1.0.yml up -d
services:
  # 部署前端项目
  wuwa-probability-front:
    image: cxlian/wuwa-probability-front:1.0
    container_name: wuwa-probability-front
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/html:/usr/share/nginx/html
    privileged: true
  # 部署后端项目
  wuwa-probability:
    image: cxlian/wuwa-probability:1.0
    container_name: wuwa-probability-app
    restart: on-failure
    ports:
      - "8091:8091"
    environment:
      - TZ=PRC
      - SERVER_PORT=8091
    volumes:
      - ./log:/data/log
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - my-network


networks:
  my-network:
    driver: bridge
