version: '3.8'

services:
  webapp:
    image: cxlian/wuwa-probability:1.0
    ports:
      - "8091:8091"  # 主机端口:容器端口
    environment:
      - SPRING_PROFILES_ACTIVE=prod  # 示例环境变量
    restart: unless-stopped  # 异常退出时自动重启
    volumes:
      - ./logs:/app/logs  # 挂载日志目录（按需配置）
    networks:
      - app-network

# 自定义网络（可选）
networks:
  app-network:
    driver: bridge
